### PR TITLE
Ms codes

### PR DESCRIPTION
**Pull request by mattretzer**
Hi @ericawarren , please take a look when you get a chance!  Just added data validation for the Style-codes column:)

### CODE REVIEW

**Review by ericawarren — CHANGES_REQUESTED** [review]
We should pull the codes directly from the stye names rather than enter directly, so it can't be OK in the MS_Code column but wrong in the actual style name. This formula in the MS_Code column should do it (with $A4 replaced with the current row number, which Fill > Down would do for you):
`=TRIM(RIGHT($A4,LEN($A4)-SEARCH(" (",$A4)))`

**Comment by mattretzer** [comment]
@ericawarren  I just tried it..  But the validation's not working that way; If I update to a duplicate style code in the Style Name column it's _allowing_ the duplicate in the MS_code column.  It only validates if I directly enter code into the cell :(   I think we'll get that piece the other way around when we are directly composing the Style Name from its parts?  

Or if you'd rather I can split the names into 2 pieces (name, code) now and have the Style name = those put together, for now?   Actually, then I could validate the Name _and_ the Code columns, and protect the Style_Name column so it cannot be directly entered.

**Comment by mattretzer** [comment]
@ericawarren : OK, I went ahead and did that (split current names into names + code columns with validation, and made a protected column with 'full style name' composed from those)...  It made too much sense!  I also patched up some data validation stuff that I noticed as I started to enter new styles.  

Plz don't re-review quite yet, I want to keep all this stuff but it will change more if the priority setting works.

**Comment by mattretzer** [comment]
@ericawarren OK, _Now_ I'm ready for another review ;)  The Priorities work!  I added a Sub to change all builtin styles to priority 9 - everything else we can set in the order we want for the style menu (Right now all Para styles are 1 and spans are 2)

**Review by ericawarren — APPROVED** [review]

**Comment by ericawarren** [comment]
Good job figuring that out! :clap:

**Pull request merged**
