### PR TITLE
Adding HTML Data

### PR DESCRIPTION
**Pull request by nelliemckesson**
Adding some extra columns with html mapping data. 

@mattretzer or @ericawarren can you review?

### CODE REVIEW

**Comment by mattretzer** [comment]
Hi @nelliemckesson, I'm taking a look and testing json export.   FYI Erica has a PR involving this file too https://github.com/macmillanpublishers/Word-template_assets/pull/12, so we will need to merge one first and then the other. I would suggest hers first since she appears to have more granular changes & yours is a more discrete block of stuff that could be pasted after?

**Comment by nelliemckesson** [comment]
@mattretzer that's probably fine. If she added new styles, then I'll have to adjust mine a bit for that.

**Comment by ericawarren** [comment]
@nelliemckesson do you need the HTML data to be present in the output JSON? If so, it will probably need values in row 3 to serve as keys for those values, and then you'll need to run the .bat again on a PC. 

@mattretzer can you confirm that? And if she does that and we merge the JSON files, can we import those back into the spreadsheet or will that break all the validation?

**Comment by nelliemckesson** [comment]
@ericawarren nope, none of my stuff needs to be in the json! It's purely for reference.

**Comment by mattretzer** [comment]
@ericawarren I do think there will need to be content in Row 3 or the whole export may fail - I tested once before I got sidetracked and it failed.  Also the autofilter probably needs to be added to the rest of Row 3; so they are included in the sort.  
I guess I could add a header in row 3 that includes a string like 'nojson' and then they wouldn't be exported & needlessly bloat the json?

Also btw the export from excel to json should work on a Mac in Excel 2011, (though it's a fair bit slower).  It's the creating the templates in Office for Mac where we lose functionality.

Maybe we should finish your PR, then I'll add a bit for 'noJSON' header, + a patch for the validation, & put Nellie's stuff back in, then she can update for new styles you've created?  Does that sound ok?

**Comment by mattretzer** [comment]
I fixed the issue with 0's not permitted in certain columns; and now any column without an entry in row 3 won't export to the json. I also put all of Nellie's bookmaker columns & data back in.  
So @nelliemckesson it's back to you to make whatever changes you need to make!  Let me know if you have any issues with protection on the sheet ;)

**Comment by nelliemckesson** [comment]
Ok @mattretzer @ericawarren this is ready for review again!

**Review by mattretzer — APPROVED** [review]

**Pull request merged**
